--- # Vault example
- hosts: localhost
  vars_files:
    /home/ansible/vault
  tasks:
    - name: Add secret text to open.txt
      lineinfile:
        path: /home/ansible/open.txt
        create: yes
        line: "{{ password }}"
      no_log: true
